// Code generated by protoc-gen-go. DO NOT EDIT.
// source: staff.proto

/*
Package staff is a generated protocol buffer package.

It is generated from these files:
	staff.proto

It has these top-level messages:
	NilResult
	GetAuthStatusRequest
	GetAuthStatusResult
	GetUserRequest
	UpdateUserRequest
	User
*/
package staff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequestSearchType int32

const (
	GetUserRequest_ID      GetUserRequestSearchType = 0
	GetUserRequest_TSDBID  GetUserRequestSearchType = 1
	GetUserRequest_TSUUID  GetUserRequestSearchType = 2
	GetUserRequest_EMAIL   GetUserRequestSearchType = 3
	GetUserRequest_STEAMID GetUserRequestSearchType = 4
	GetUserRequest_TOKEN   GetUserRequestSearchType = 5
)

var GetUserRequestSearchType_name = map[int32]string{
	0: "ID",
	1: "TSDBID",
	2: "TSUUID",
	3: "EMAIL",
	4: "STEAMID",
	5: "TOKEN",
}
var GetUserRequestSearchType_value = map[string]int32{
	"ID":      0,
	"TSDBID":  1,
	"TSUUID":  2,
	"EMAIL":   3,
	"STEAMID": 4,
	"TOKEN":   5,
}

func (x GetUserRequestSearchType) String() string {
	return proto.EnumName(GetUserRequestSearchType_name, int32(x))
}
func (GetUserRequestSearchType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type NilResult struct {
}

func (m *NilResult) Reset()                    { *m = NilResult{} }
func (m *NilResult) String() string            { return proto.CompactTextString(m) }
func (*NilResult) ProtoMessage()               {}
func (*NilResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetAuthStatusRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetAuthStatusRequest) Reset()                    { *m = GetAuthStatusRequest{} }
func (m *GetAuthStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAuthStatusRequest) ProtoMessage()               {}
func (*GetAuthStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAuthStatusRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetAuthStatusResult struct {
	Admin int32 `protobuf:"varint,1,opt,name=admin" json:"admin,omitempty"`
}

func (m *GetAuthStatusResult) Reset()                    { *m = GetAuthStatusResult{} }
func (m *GetAuthStatusResult) String() string            { return proto.CompactTextString(m) }
func (*GetAuthStatusResult) ProtoMessage()               {}
func (*GetAuthStatusResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAuthStatusResult) GetAdmin() int32 {
	if m != nil {
		return m.Admin
	}
	return 0
}

type GetUserRequest struct {
	Search string                   `protobuf:"bytes,1,opt,name=search" json:"search,omitempty"`
	Type   GetUserRequestSearchType `protobuf:"varint,2,opt,name=type,enum=staff.GetUserRequestSearchType" json:"type,omitempty"`
	Token  string                   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GetUserRequest) GetType() GetUserRequestSearchType {
	if m != nil {
		return m.Type
	}
	return GetUserRequest_ID
}

func (m *GetUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdateUserRequest struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	Id              string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TsName          string `protobuf:"bytes,2,opt,name=tsName" json:"tsName,omitempty"`
	Tsdbid          string `protobuf:"bytes,3,opt,name=tsdbid" json:"tsdbid,omitempty"`
	Tsuuid          string `protobuf:"bytes,4,opt,name=tsuuid" json:"tsuuid,omitempty"`
	Tscreated       string `protobuf:"bytes,5,opt,name=tscreated" json:"tscreated,omitempty"`
	Tslastconnected string `protobuf:"bytes,6,opt,name=tslastconnected" json:"tslastconnected,omitempty"`
	Email           string `protobuf:"bytes,7,opt,name=email" json:"email,omitempty"`
	Joindate        string `protobuf:"bytes,8,opt,name=joindate" json:"joindate,omitempty"`
	Dob             string `protobuf:"bytes,9,opt,name=dob" json:"dob,omitempty"`
	Gender          string `protobuf:"bytes,10,opt,name=gender" json:"gender,omitempty"`
	Active          bool   `protobuf:"varint,11,opt,name=active" json:"active,omitempty"`
	Admin           int32  `protobuf:"varint,12,opt,name=admin" json:"admin,omitempty"`
	Steamid         string `protobuf:"bytes,13,opt,name=steamid" json:"steamid,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetTsName() string {
	if m != nil {
		return m.TsName
	}
	return ""
}

func (m *User) GetTsdbid() string {
	if m != nil {
		return m.Tsdbid
	}
	return ""
}

func (m *User) GetTsuuid() string {
	if m != nil {
		return m.Tsuuid
	}
	return ""
}

func (m *User) GetTscreated() string {
	if m != nil {
		return m.Tscreated
	}
	return ""
}

func (m *User) GetTslastconnected() string {
	if m != nil {
		return m.Tslastconnected
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetJoindate() string {
	if m != nil {
		return m.Joindate
	}
	return ""
}

func (m *User) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *User) GetAdmin() int32 {
	if m != nil {
		return m.Admin
	}
	return 0
}

func (m *User) GetSteamid() string {
	if m != nil {
		return m.Steamid
	}
	return ""
}

func init() {
	proto.RegisterType((*NilResult)(nil), "staff.NilResult")
	proto.RegisterType((*GetAuthStatusRequest)(nil), "staff.GetAuthStatusRequest")
	proto.RegisterType((*GetAuthStatusResult)(nil), "staff.GetAuthStatusResult")
	proto.RegisterType((*GetUserRequest)(nil), "staff.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "staff.UpdateUserRequest")
	proto.RegisterType((*User)(nil), "staff.User")
	proto.RegisterEnum("staff.GetUserRequestSearchType", GetUserRequestSearchType_name, GetUserRequestSearchType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Staff service

type StaffClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*NilResult, error)
	AuthStatus(ctx context.Context, in *GetAuthStatusRequest, opts ...grpc.CallOption) (*GetAuthStatusResult, error)
}

type staffClient struct {
	cc *grpc.ClientConn
}

func NewStaffClient(cc *grpc.ClientConn) StaffClient {
	return &staffClient{cc}
}

func (c *staffClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/staff.staff/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*NilResult, error) {
	out := new(NilResult)
	err := grpc.Invoke(ctx, "/staff.staff/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffClient) AuthStatus(ctx context.Context, in *GetAuthStatusRequest, opts ...grpc.CallOption) (*GetAuthStatusResult, error) {
	out := new(GetAuthStatusResult)
	err := grpc.Invoke(ctx, "/staff.staff/AuthStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Staff service

type StaffServer interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*NilResult, error)
	AuthStatus(context.Context, *GetAuthStatusRequest) (*GetAuthStatusResult, error)
}

func RegisterStaffServer(s *grpc.Server, srv StaffServer) {
	s.RegisterService(&_Staff_serviceDesc, srv)
}

func _Staff_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staff.staff/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Staff_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staff.staff/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Staff_AuthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServer).AuthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staff.staff/AuthStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServer).AuthStatus(ctx, req.(*GetAuthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Staff_serviceDesc = grpc.ServiceDesc{
	ServiceName: "staff.staff",
	HandlerType: (*StaffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Staff_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Staff_UpdateUser_Handler,
		},
		{
			MethodName: "AuthStatus",
			Handler:    _Staff_AuthStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staff.proto",
}

func init() { proto.RegisterFile("staff.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x49, 0xa6, 0xe9, 0xcf, 0x0d, 0x94, 0x60, 0x06, 0x64, 0x15, 0x24, 0xaa, 0xac, 0x2a,
	0x01, 0x5d, 0x14, 0x16, 0x6c, 0x8b, 0x52, 0x8d, 0x02, 0x4c, 0x47, 0x4a, 0xdb, 0x07, 0x70, 0xe3,
	0x3b, 0x8c, 0xa1, 0x4d, 0x4a, 0xec, 0x20, 0xcd, 0x93, 0xf1, 0x04, 0x6c, 0x78, 0x2a, 0xe4, 0x9f,
	0x4e, 0x42, 0x99, 0x9d, 0xbf, 0x73, 0x4f, 0x6e, 0x8e, 0xed, 0x6b, 0x08, 0xa5, 0x62, 0xd7, 0xd7,
	0xd3, 0x43, 0x55, 0xaa, 0x92, 0x04, 0x06, 0xe2, 0x10, 0x06, 0x4b, 0xb1, 0xcb, 0x50, 0xd6, 0x3b,
	0x15, 0xbf, 0x81, 0xf3, 0x0b, 0x54, 0xf3, 0x5a, 0xdd, 0xac, 0x14, 0x53, 0xb5, 0xcc, 0xf0, 0x47,
	0x8d, 0x52, 0x91, 0x73, 0x08, 0x54, 0xf9, 0x1d, 0x0b, 0xea, 0x8d, 0xbd, 0xc9, 0x20, 0xb3, 0x10,
	0xbf, 0x86, 0xa7, 0x27, 0x6e, 0xdd, 0x44, 0x9b, 0x19, 0xdf, 0x0b, 0x6b, 0x0e, 0x32, 0x0b, 0xf1,
	0x6f, 0x0f, 0x86, 0x17, 0xa8, 0x36, 0x12, 0xab, 0x63, 0xd7, 0xe7, 0xd0, 0x95, 0xc8, 0xaa, 0xfc,
	0xc6, 0xb5, 0x75, 0x44, 0xde, 0x43, 0x47, 0xdd, 0x1e, 0x90, 0xfa, 0x63, 0x6f, 0x32, 0x9c, 0x8d,
	0xa7, 0x36, 0xf5, 0xbf, 0x1f, 0x4f, 0xad, 0x77, 0x7d, 0x7b, 0xc0, 0xcc, 0xb8, 0x9b, 0x8c, 0x67,
	0xed, 0x8c, 0x57, 0x00, 0x8d, 0x93, 0x74, 0xc1, 0x4f, 0x93, 0xe8, 0x01, 0x01, 0xe8, 0xae, 0x57,
	0xc9, 0xc7, 0x34, 0x89, 0x3c, 0xbb, 0xde, 0x6c, 0xd2, 0x24, 0xf2, 0xc9, 0x00, 0x82, 0xc5, 0xe5,
	0x3c, 0xfd, 0x12, 0x9d, 0x91, 0x10, 0x7a, 0xab, 0xf5, 0x62, 0x7e, 0x99, 0x26, 0x51, 0x47, 0xeb,
	0xeb, 0xab, 0xcf, 0x8b, 0x65, 0x14, 0xc4, 0x9f, 0xe0, 0xc9, 0xe6, 0xc0, 0x99, 0xc2, 0xf6, 0x4e,
	0x5e, 0x41, 0xa7, 0x96, 0x58, 0x99, 0x7d, 0x84, 0xb3, 0xd0, 0x25, 0x36, 0x0e, 0x53, 0x68, 0xc2,
	0xf9, 0xed, 0x70, 0x7f, 0x7c, 0xe8, 0x68, 0x13, 0x19, 0x82, 0x2f, 0xb8, 0x3b, 0x05, 0x5f, 0x70,
	0x7d, 0x32, 0x4a, 0x2e, 0xd9, 0x1e, 0x9d, 0xdf, 0x91, 0xd5, 0xf9, 0x56, 0x70, 0xb7, 0x49, 0x47,
	0x56, 0xaf, 0x6b, 0xc1, 0x69, 0xe7, 0xa8, 0x6b, 0x22, 0x2f, 0x61, 0xa0, 0x64, 0x5e, 0x21, 0x53,
	0xc8, 0x69, 0x60, 0x4a, 0x8d, 0x40, 0x26, 0xf0, 0x58, 0xc9, 0x1d, 0x93, 0x2a, 0x2f, 0x8b, 0x02,
	0x73, 0xed, 0xe9, 0x1a, 0xcf, 0xa9, 0xac, 0xe3, 0xe3, 0x9e, 0x89, 0x1d, 0xed, 0xd9, 0xf8, 0x06,
	0xc8, 0x08, 0xfa, 0xdf, 0x4a, 0x51, 0xe8, 0xc3, 0xa0, 0x7d, 0x53, 0xb8, 0x63, 0x12, 0xc1, 0x19,
	0x2f, 0xb7, 0x74, 0x60, 0x64, 0xbd, 0xd4, 0x19, 0xbf, 0x62, 0xc1, 0xb1, 0xa2, 0x60, 0x33, 0x5a,
	0xd2, 0x3a, 0xcb, 0x95, 0xf8, 0x89, 0x34, 0x1c, 0x7b, 0x93, 0x7e, 0xe6, 0xa8, 0x19, 0xa3, 0x87,
	0xad, 0x31, 0x22, 0x14, 0x7a, 0x52, 0x21, 0xdb, 0x0b, 0x4e, 0x1f, 0x99, 0x36, 0x47, 0x9c, 0xfd,
	0xf2, 0xc0, 0x8e, 0x34, 0x79, 0x0b, 0x3d, 0x37, 0x2c, 0xe4, 0xd9, 0xbd, 0xc3, 0x33, 0x6a, 0xdf,
	0x10, 0xf9, 0x00, 0xd0, 0xdc, 0x28, 0xa1, 0xc7, 0xd2, 0xe9, 0x25, 0x8f, 0x22, 0x57, 0xb9, 0x7b,
	0x2e, 0x64, 0x01, 0xd0, 0x4c, 0x3f, 0x79, 0xd1, 0xfc, 0xeb, 0xbf, 0x17, 0x34, 0x1a, 0xdd, 0x5f,
	0xd4, 0x6d, 0xb6, 0x5d, 0xf3, 0x20, 0xdf, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xe1, 0x37,
	0xfa, 0x9f, 0x03, 0x00, 0x00,
}
